### ISSUE TITLE
Unable to complete directory listing with invalid UTF8 characters

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/pyftpdlib#280]
_From [d...@devicenull.org](https://code.google.com/u/116065553983501399508/) on February 04, 2014 23:26:12_

```
We had a user manage to get an invalid UTF8 byte sequence in one of their file 
names (I believe this was done through external software, not uploading a file 
via FTP).  After that, they were no longer able to retrieve a directory list, 
the FTP server threw the following exception:

ERROR unhandled exception in instance <pyftpdlib.handlers.TLS_DTPHandler object 
at 0x8f3ca2c>
Traceback (most recent call last):
File "pyftpdlib.handlers", line 1658, in push_dtp_data
File "pyftpdlib.handlers", line 599, in push_with_producer
File "asynchat", line 190, in push_with_producer
File "pyftpdlib.handlers", line 605, in initiate_send
File "asynchat", line 226, in initiate_send
File "pyftpdlib.handlers", line 992, in more
File "pyftpdlib.filesystems", line 564, in format_mlsx
File "encodings.utf_8", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 43: invalid 
continuation byte


I'm afraid I don't have any way of determining which filename was the issue, 
but our workaround for this was this patch:

--- a/pyftpdlib-1.2.0/pyftpdlib/filesystems.py
+++ b/pyftpdlib-1.2.0/pyftpdlib/filesystems.py
@@ -448,7 +448,7 @@ class AbstractedFS(object):
                     # http://bugs.python.org/issue683592 file = 
os.path.join(bytes(basedir), bytes(basename))
                     if not isinstance(basename, unicode):
-                        basename = unicode(basename, 'utf8')
+                        basename = unicode(basename, 'utf8', 'ignore')
             else:
                 file = os.path.join(basedir, basename)
             try:
@@ -561,7 +561,7 @@ class AbstractedFS(object):
                     # http://bugs.python.org/issue683592 file = 
os.path.join(bytes(basedir), bytes(basename))
                     if not isinstance(basename, unicode):
-                        basename = unicode(basename, 'utf8')
+                        basename = unicode(basename, 'utf8', 'ignore')
             else:
                 file = os.path.join(basedir, basename)
             # in order to properly implement 'unique' fact (RFC-3659,
```

_Original issue: http://code.google.com/p/pyftpdlib/issues/detail?id=280_

**Comment by edescourtis** [comment]
[E 2015-05-28 10:31:20] unhandled exception in instance <pyftpdlib.handlers.DTPHandler (addr=127.0.0.1:29691, user=u'eric', receive=False, file='') at 0x34dd6c8>
    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1714, in push_dtp_data
        self.data_channel.push_with_producer(data)
      File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 653, in push_with_producer
        AsyncChat.push_with_producer(self, producer)
      File "/usr/lib/python2.7/asynchat.py", line 190, in push_with_producer
        self.initiate_send()
      File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 659, in initiate_send
        asynchat.async_chat.initiate_send(self)
      File "/usr/lib/python2.7/asynchat.py", line 226, in initiate_send
        data = first.more()
      File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1048, in more
        buffer.append(next(self.iterator))
      File "build/bdist.linux-x86_64/egg/pyftpdlib/filesystems.py", line 506, in format_list
        perms, nlinks, uname, gname, size, mtimestr, basename)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 15: ordinal not in range(128)
