### ISSUE TITLE
TypeError when using a recent version of PyOpenSSL

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/pyftpdlib#296]
Original issue:
https://groups.google.com/forum/#!topic/pyftpdlib/V0cEhHvG5JA

Traceback:

```
test_banner (__main__.TestConfigurableOptionsTLSMixin) ... unhandled exception in instance <pyftpdlib.handlers.TLS_FTPHandler object at 0x7fdf47614d50>
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 3053, in handle_read_event
    super(SSLConnection, self).handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/asynchat.py", line 158, in handle_read
    self.found_terminator()
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1378, in found_terminator
    self.pre_process_command(line, cmd, arg)
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1427, in pre_process_command
    self.process_command(cmd, arg)
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 3324, in process_command
    FTPHandler.process_command(self, cmd, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1495, in process_command
    method(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 2415, in ftp_USER
    self.respond('331 Username ok, send password.')
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1682, in respond
    self.push(resp + '\r\n')
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 1677, in push
    asynchat.async_chat.push(self, s.encode('utf8'))
  File "/usr/lib/python2.7/asynchat.py", line 186, in push
    self.initiate_send()
  File "build/bdist.linux-x86_64/egg/pyftpdlib/ioloop.py", line 927, in initiate_send
    asynchat.async_chat.initiate_send(self)
  File "/usr/lib/python2.7/asynchat.py", line 235, in initiate_send
    num_sent = self.send(data)
  File "build/bdist.linux-x86_64/egg/pyftpdlib/handlers.py", line 3081, in send
    return super(SSLConnection, self).send(data)
  File "build/bdist.linux-x86_64/egg/pyftpdlib/ioloop.py", line 896, in send
    return self.socket.send(data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 947, in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string
```

To me this happens after an upgrade of PyOpenSSL

**Comment by CheshtaShyngle25** [comment]
I am getting the same error as mentioned above.How to fix this ?

**Comment by CheshtaShyngle25** [comment]
It got solved using pyOpenSSL0.13. Thank You.

**Comment by giampaolo** [comment]
Cool.
