### ISSUE TITLE
Error: unhandled exception

### ISSUE THREAD

**Issue by cleve** [giampaolo/pyftpdlib#394]
Hello, I am having errors when the server receives files every 25 secs, the error is shown after 15-20 hours of working, and the server crashes. The detail of the error is: 

Version: 1.5.1
Python: 2.7
OS: Ubuntu server 14.04

```
ERROR:pyftpdlib:unhandled exception in instance <core.watcher.MyHandler (addr=X.X.X.X:X, user=u'my_user')>
Traceback (most recent call last):
  File "/usr/lib/python2.7/asynchat.py", line 110, in handle_read
    data = self.recv (self.ac_in_buffer_size)
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 898, in recv
    data = self.socket.recv(buffer_size)
error: [Errno 110] Connection timed out
```

Finally I came back to the v1.4.0

Regards.

**Comment by giampaolo** [comment]
Fixed.
