### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor on OSX

### ISSUE THREAD

**Issue by JonathanHerrmann** [giampaolo/pyftpdlib#430]
When running tests on my project with Linux they work fine, but with OSX I get this error:

```
python /Users/w/.virtualenvs/controller_config/lib/python3.5/site-packages/pytest_localftpserver/plugin.py
FTPD running on port 30123
[I 2017-08-01 16:02:03] >>> starting FTP server on 127.0.0.1:30123, pid=32856 <<<
[I 2017-08-01 16:02:03] concurrency model: async
[I 2017-08-01 16:02:03] masquerade (NAT) address: None
[I 2017-08-01 16:02:03] passive ports: None
Process MPFTPServer-1:
Traceback (most recent call last):
  File "/opt/pkg/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/w/.virtualenvs/controller_config/lib/python3.5/site-packages/pytest_localftpserver/plugin.py", line 81, in run
    self._server.serve_forever()
  File "/Users/w/.virtualenvs/controller_config/lib/python3.5/site-packages/pyftpdlib/servers.py", line 207, in serve_forever
    self.ioloop.loop(timeout, blocking)
  File "/Users/w/.virtualenvs/controller_config/lib/python3.5/site-packages/pyftpdlib/ioloop.py", line 348, in loop
    poll(soonest_timeout)
  File "/Users/w/.virtualenvs/controller_config/lib/python3.5/site-packages/pyftpdlib/ioloop.py", line 709, in poll
    timeout)
OSError: [Errno 9] Bad file descriptor
```

**Comment by lithammer** [comment]
For anyone else coming here. I managed to solve this by passing `timeout=1.0` to `.serve_forever()`.
