### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by adamgotterer** [giampaolo/pyftpdlib#437]
When switching to passive mode and then issuing a command the server crashes with: `AttributeError: 'bool' object has no attribute 'startswith'`

```bash
ftp> open 127.0.0.1 2121
Connected to 127.0.0.1.
220 pyftpdlib 1.5.2 ready.
Name (127.0.0.1:adam): user
331 Username ok, send password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
501 Rejected data connection to foreign address 127.0.0.1:50043.
ftp> passive
Passive mode: on; fallback to active mode: on.
ftp>
ftp> ls
421 Service not available, remote server has closed connection.
```

```
svc-ftp_1   | [I 2017-10-12 02:54:45] 172.18.0.1:56532-[] FTP session opened (connect)
svc-ftp_1   | [I 2017-10-12 02:54:49] 172.18.0.1:56532-[user] USER 'user' logged in.
svc-ftp_1   | [W 2017-10-12 02:54:50] 172.18.0.1:56532-[user] Rejected data connection to foreign address 127.0.0.1:50043.
svc-ftp_1   | [W 2017-10-12 02:54:50] 172.18.0.1:56532-[user] Rejected data connection to foreign address 127.0.0.1:50043.
svc-ftp_1   | [E 2017-10-12 02:54:56] unhandled exception in instance <FTPHandler(id=140127626802512, addr='172.18.0.1:56532', user='user')>
svc-ftp_1   |     Traceback (most recent call last):
svc-ftp_1   |       File "/usr/local/lib/python3.6/asyncore.py", line 83, in read
svc-ftp_1   |         obj.handle_read_event()
svc-ftp_1   |       File "/usr/local/lib/python3.6/asyncore.py", line 423, in handle_read_event
svc-ftp_1   |         self.handle_read()
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/ioloop.py", line 920, in handle_read
svc-ftp_1   |         asynchat.async_chat.handle_read(self)
svc-ftp_1   |       File "/usr/local/lib/python3.6/asynchat.py", line 171, in handle_read
svc-ftp_1   |         self.found_terminator()
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/handlers.py", line 1404, in found_terminator
svc-ftp_1   |         self.pre_process_command(line, cmd, arg)
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/handlers.py", line 1510, in pre_process_command
svc-ftp_1   |         self.process_command(cmd, arg, **kwargs)
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/handlers.py", line 1521, in process_command
svc-ftp_1   |         method(*args, **kwargs)
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/handlers.py", line 2030, in ftp_PASV
svc-ftp_1   |         self._make_epasv(extmode=False)
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/handlers.py", line 1948, in _make_epasv
svc-ftp_1   |         self._dtp_acceptor = self.passive_dtp(self, extmode)
svc-ftp_1   |       File "/usr/local/lib/python3.6/site-packages/pyftpdlib/handlers.py", line 348, in __init__
svc-ftp_1   |         if ip.startswith('::ffff:'):
svc-ftp_1   |     AttributeError: 'bool' object has no attribute 'startswith'
svc-ftp_1   | [I 2017-10-12 02:54:56] 172.18.0.1:56532-[user] FTP session closed (disconnect).
```

```python
from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer

authorizer = DummyAuthorizer()
authorizer.add_user("user", "12345", "/ftp_root/user", perm="elradfmw")

handler = FTPHandler
handler.authorizer = authorizer
handler.passive_ports = range(50000, 50100)
handler.masquerade_address = True

server = FTPServer(("0.0.0.0", 2121), handler)
server.serve_forever()
```

**Comment by giampaolo** [comment]
This is the culprit line: `handler.masquerade_address = True`. That should be a string (an IP address), not a bool.
