### ISSUE TITLE
mget wildcard support

### ISSUE THREAD

**Issue by baberuth22** [giampaolo/pyftpdlib#445]
We launched our new servrer last night and a client is trying to get all files using mget *.   Does this server support mget?    Any  idea how to enable it?

URGENT :)

thanks!

**Comment by giampaolo** [comment]
I'm not sure what `mget *` does, nor I know what FTP client you're talking about. Just try it.

**Comment by baberuth22** [comment]
It is new to me as well, but we must support it.  I believe they run it directly on their server command line style.   

Mget is an ftp subcommand which copies multiple files from the remote system to the local system.   It allows an asterisk to select all members of a folder and download at once.  https://www.thesqlreport.com/?p=143

**Comment by baberuth22** [comment]
We can use mget to get a specific file, but the wildcard does not work.   Here is a suggested solution to turn off file globbing.   https://stackoverflow.com/a/20766410/55124

**Comment by giampaolo** [comment]
It all depends on what **FTP command** this "mget *" instruction sends to the server.  If it's a standard RFC-959 FTP command then it will work.

**Comment by baberuth22** [comment]
It is a standard FTP command, and it works, just not with the wildcard.  https://www.serv-u.com/features/file-transfer-protocol-server-linux/commands

**Comment by giampaolo** [comment]
Define "not work". Please attach the server logs (in debug mode) and let's see what command is sent and why it is rejected.

**Comment by baberuth22** [comment]
To toggle file globbing, I use the glob command.   Here is an example:

tp> glob
Globbing off.
ftp> mget *.php
local: *.php remote: *.php
229 Entering extended passive mode (|||43493|).
550 No such file or directory.
ftp> glob
Globbing on.
ftp> mget *.php
No such file or directory.

**Comment by giampaolo** [comment]
**server** logs, not client logs

**Comment by baberuth22** [comment]
FTP server logs?

[I 17-11-09 12:50:01] 169.55.220.118:46152-[] FTP session opened (connect)
[I 17-11-09 12:50:01] 169.55.220.118:46152-[fullcircle] USER 'fullcircle' logged in.
[I 17-11-09 12:50:01] 169.55.220.118:46152-[fullcircle] CWD /srv/users/serverpilot/apps/circlify/public/app/transfer/seavees/outgoing 250
[I 17-11-09 12:50:01] 169.55.220.118:46152-[fullcircle] FTP session closed (disconnect).
[I 17-11-09 12:50:02] 169.55.220.118:46154-[] FTP session opened (connect)
[I 17-11-09 12:50:02] 169.55.220.118:46154-[fullcircle] USER 'fullcircle' logged in.
[I 17-11-09 12:50:02] 169.55.220.118:46154-[fullcircle] CWD /srv/users/serverpilot/apps/circlify/public/app/transfer/seavees/incoming 250
[I 17-11-09 12:50:02] 169.55.220.118:46154-[fullcircle] STOR /srv/users/serverpilot/apps/circlify/public/app/transfer/seavees/incoming/03_RA_Export_11254726659_20171109111101_result.txt completed=1 bytes=192 seconds=0.078
[I 17-11-09 12:50:02] Starting new HTTP connection (1): circlify.net
[I 17-11-09 12:50:03] 169.55.220.118:46154-[fullcircle] FTP session closed (disconnect).
[I 17-11-09 12:50:06] 12.26.105.51:36094-[] FTP session opened (connect)
[I 17-11-09 12:50:06] 12.26.105.51:36094-[pelagic] USER 'pelagic' logged in.
[I 17-11-09 12:50:06] 12.26.105.51:36094-[pelagic] CWD /srv/users/serverpilot/apps/circlify/public/app/transfer/pelagic/outgoing 250
[I 17-11-09 12:50:06] 12.26.105.51:36094-[pelagic] FTP session closed (disconnect).
[I 17-11-09 12:50:07] 169.55.220.125:40602-[] FTP session opened (connect)
[I 17-11-09 12:50:07] 169.55.220.125:40602-[raen] USER 'raen' logged in.
[I 17-11-09 12:50:07] 169.55.220.125:40602-[raen] CWD /srv/users/serverpilot/apps/circlify/public/app/transfer/raen/incoming 250
[I 17-11-09 12:50:08] 169.55.220.125:40602-[raen] STOR /srv/users/serverpilot/apps/circlify/public/app/transfer/raen/incoming/RAEN_B6_Inventory.txt completed=1 bytes=38398 seconds=0.116
[I 17-11-09 12:50:08] Starting new HTTP connection (1): circlify.net
[I 17-11-09 12:50:08] 169.55.220.118:46160-[] FTP session opened (connect)
[I 17-11-09 12:50:08] 169.55.220.125:40602-[raen] FTP session closed (disconnect).
[I 17-11-09 12:50:08] 169.55.220.118:46160-[fullcircle] USER 'fullcircle' logged in.
[I 17-11-09 12:50:08] 169.55.220.118:46160-[fullcircle] CWD /srv/users/serverpilot/apps/circlify/public/app/transfer/seavees/incoming 250
[I 17-11-09 12:50:08] 169.55.220.118:46160-[fullcircle] STOR /srv/users/serverpilot/apps/circlify/public/app/transfer/seavees/incoming/03_RA_Export_11456970755_20171109111137_result.txt completed=1 bytes=192 seconds=0.079
[I 17-11-09 12:50:08] Starting new HTTP connection (1): circlify.net
[I 17-11-09 12:50:09] 169.55.220.118:46160-[fullcircle] FTP session closed (disconnect).
[I 17-11-09 12:50:10] 65.52.192.109:49512-[] FTP session opened (connect)
[I 17-11-09 12:50:16] 65.52.192.109:49512-[] USER 'ramp_nde' failed login.
[I 17-11-09 12:50:16] 65.52.192.109:49512-[] FTP session closed (disconnect).

**Comment by baberuth22** [comment]
Seems it's not throwing any errors

**Comment by giampaolo** [comment]
This server log extract does not refer to the client log you pasted above (there's are no 550 errors).

**Comment by baberuth22** [comment]
What about this error log?

Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "ftpserver.py", line 118, in 
main()
File "ftpserver.py", line 109, in main
server = FTPServer(address, handler)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 145, in init
self._af = self.bind_af_unspecified(address_or_socket)
File "/usr/lib/python2.7/dist-packages/pyftpdlib/ioloop.py", line 732, in bind_af_unspecified
raise socket.error(err)
socket.error: [Errno 98] Address already in use

**Comment by baberuth22** [comment]
Is that a client log too?   Where would I find the correct error log?

**Comment by giampaolo** [comment]
This has nothing to do with your original question. Dude listen, this is a programming library meant for Python developers, not an end-user FTP server. As such you **have** to know Python in order to use it. If you don't (which is totally fine) I strongly recommend to use another FTP server. If you're on Windows I recommend FileZilla. If you're on UNIX either proftpd or vsftpd.

**Comment by baberuth22** [comment]
Filezilla as an FTP server?   I am not making a client.  Our application requires FTP as a data integration point so our clients can use Filezilla or whatever to download files from our server.   

We are trying to host an FTP server and the wildcard does not work with mget commands.

**Comment by giampaolo** [comment]
FileZilla also exists as a server: https://wiki.filezilla-project.org/FileZilla_FTP_Server

**Comment by baberuth22** [comment]
I guess I will try another ftp server.   It's unfortunate because this one was worked like a charm with the exception of mget *.

**Comment by baberuth22** [comment]
After evaluating the alternatives, we'd love to still use this library.  We'd be happy to hire you to resolve the mget wildcard issue on our server if you're interested.

**Comment by giampaolo** [comment]
OK then, not sure if I will have enough time but mail me at g.rodola@gmail.com.

**Comment by baberuth22** [comment]
Thanks @giampaolo.   My associate just sent you an email.

**Comment by baberuth22** [comment]
I believe this references the problem.  https://github.com/giampaolo/pyftpdlib/issues/106

**Comment by neurogeometry** [comment]
It looks like a bug to me. I finally used "urlwrite" function and it works fine for me. I'm using MATLAB R2017a.
Something like this:
LocalFilePath = urlwrite('ftp://someaddress.org:8811/dong/retrograde/image.tif', 'image.tif');
