### ISSUE TITLE
logger.debug

### ISSUE THREAD

**Issue by fabltd** [giampaolo/pyftpdlib#457]
New build.

Running into the following error preventing startup.  
```
 server.serve_forever()

  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 205, in serve_forever
    self._log_start()
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 174, in _log_start
    logger.debug("use sendfile(2): %s", self.handler.use_sendfile)

AttributeError: class MyHandler has no attribute 'use_sendfile'
root@debug:/home/pi/ftp# python /usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 45, in <module>
    from .ioloop import Acceptor
ValueError: Attempted relative import in non-package

```

**Comment by giampaolo** [comment]
Mmmm what pyftpdlib version are you using? How did you install it? This looks like some kind of installation issue.

**Comment by giampaolo** [comment]
Closing out as outdated.
