### ISSUE TITLE
pyftpdlib.test.test_functional_ssl.TestTimeoutsTLSMixin.test_idle_data_timeout2 / pyftpdlib.test.test_functional.TestTimeouts.test_idle_data_timeout2 tests are flaky

### ISSUE THREAD

**Issue by Whissi** [giampaolo/pyftpdlib#470]
Hi,

on my x86 system, the following tests are randomly failing (not always!):

- pyftpdlib.test.test_functional_ssl.TestTimeoutsTLSMixin.test_idle_data_timeout2
- pyftpdlib.test.test_functional.TestTimeouts.test_idle_data_timeout2

Error is
```
# python2.7 -m unittest pyftpdlib.test.test_functional_ssl.TestTimeoutsTLSMixin.test_idle_data_timeout2 pyftpdlib.test.test_functional.TestTimeouts.test_idle_data_timeout2
EE
======================================================================
ERROR: pyftpdlib.test.test_functional_ssl.TestTimeoutsTLSMixin.test_idle_data_timeout2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyftpdlib/test/test_functional.py", line 1521, in test_idle_data_timeout2
    data = self.client.sock.recv(BUFSIZE)
  File "/usr/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

======================================================================
ERROR: pyftpdlib.test.test_functional.TestTimeouts.test_idle_data_timeout2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyftpdlib/test/test_functional.py", line 1521, in test_idle_data_timeout2
    data = self.client.sock.recv(BUFSIZE)
timeout: timed out

----------------------------------------------------------------------
Ran 2 tests in 2.055s

FAILED (errors=2)
vm-gentoo-x86 /tmp/pyftpdlib # python2.7 -V
Python 2.7.14
```
Seen in 1.5.3+, still present in git master.

**Comment by sbraz** [comment]
Linking back to the downstream report in case it contains important information: https://bugs.gentoo.org/659108
