### ISSUE TITLE
Alpine Linux edge v1.5.5 two failing ssl tests: test_rest_on_stor & test_stor_ascii

### ISSUE THREAD

**Issue by TBK** [giampaolo/pyftpdlib#500]
Here is the full [buildlog.txt](https://github.com/giampaolo/pyftpdlib/files/3150174/buildlog.txt)

**Failing tests:**
pyftpdlib.test.test_functional_ssl.TestFtpStoreDataTLSMixin.test_rest_on_stor
pyftpdlib.test.test_functional_ssl.TestFtpStoreDataTLSMixin.test_stor_ascii

**Errors:**
```
======================================================================
FAIL: pyftpdlib.test.test_functional_ssl.TestFtpStoreDataTLSMixin.test_rest_on_stor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tbk/Projects/aports/testing/py3-pyftpdlib/src/pyftpdlib-1.5.5/pyftpdlib/test/test_functional.py", line 899, in test_rest_on_stor
    self.assertEqual(file_size, bytes_sent)
AssertionError: 9216 != 32768

======================================================================
FAIL: pyftpdlib.test.test_functional_ssl.TestFtpStoreDataTLSMixin.test_stor_ascii
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tbk/Projects/aports/testing/py3-pyftpdlib/src/pyftpdlib-1.5.5/pyftpdlib/test/test_functional.py", line 721, in test_stor_ascii
    self.assertEqual(len(expected), len(datafile))
AssertionError: 1100000 != 1066326

----------------------------------------------------------------------
Ran 777 tests in 21.797s

FAILED (failures=2, skipped=55)
Test failed: <unittest.runner.TextTestResult run=777 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=777 errors=0 failures=2>
```

**Comment by felixonmars** [comment]
The same test failures are present on Arch too.

The environment here is:
```
platform linux -- Python 3.7.3, pytest-4.4.2, py-1.8.0, pluggy-0.11.0
```

**Comment by Apteryks** [comment]
I get these too on GNU Guix, Python 3.9.9.
